version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedbackly
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
  api:
    build:
      context: ./apps/api
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/feedbackly
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    ports:
      - '4000:4000'
    volumes:
      - ./apps/api:/app
      - /app/node_modules
  web:
    build:
      context: ./apps/web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./apps/web:/app
      - /app/node_modules
  worker:
    build:
      context: ./apps/worker
    depends_on:
      - api
    environment:
      WORKER_API_URL: http://localhost:8000
    ports:
      - '8000:8000'
    volumes:
      - ./apps/worker:/app
volumes:
  db_data: